"""
Seeds demo user accounts into auth/users.json (gitignored, regenerated by
this script, never committed -- same pattern as data/generate_synthetic_data.py
generating gitignored raw data).

These are DEMO credentials for a synthetic-data prototype only. A real
deployment would use DoD PKI/CAC authentication or an enterprise SSO/IdP,
not local username+password accounts -- this is explicitly called out in
rmf/SSP.md's IA (Identification & Authentication) control section as a
target-state gap, not something this prototype claims to have solved.

Run once (or whenever you want to reset accounts):
    python3 auth/seed_users.py
"""
import json
import os

import bcrypt

USERS_PATH = os.path.join(os.path.dirname(__file__), "users.json")

# role: "admin" sees the governance panel and the audit log; "analyst" sees
# the dashboards and the conversational query layer only. Two roles is the
# minimum needed to demonstrate role-based access control (AC-3) exists at
# all -- a real deployment would have a richer role/permission model tied
# to actual billets, not two hardcoded demo roles.
DEMO_USERS = [
    {"username": "admin", "password": "ChangeMe!Admin1", "role": "admin", "display_name": "Demo Administrator"},
    {"username": "analyst", "password": "ChangeMe!Analyst1", "role": "analyst", "display_name": "Demo Analyst"},
]


def main():
    users = []
    for u in DEMO_USERS:
        hashed = bcrypt.hashpw(u["password"].encode("utf-8"), bcrypt.gensalt())
        users.append({
            "username": u["username"],
            "password_hash": hashed.decode("utf-8"),
            "role": u["role"],
            "display_name": u["display_name"],
        })

    with open(USERS_PATH, "w") as f:
        json.dump(users, f, indent=2)

    print(f"Wrote {len(users)} demo user accounts to {USERS_PATH}")
    print("Demo credentials (CHANGE before any real use -- these are seeded in plaintext in this script):")
    for u in DEMO_USERS:
        print(f"  {u['username']} / {u['password']}  (role: {u['role']})")


if __name__ == "__main__":
    main()
